services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: quards
      POSTGRES_PASSWORD: quards
      POSTGRES_DB: quards_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: