services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: explorer
      POSTGRES_PASSWORD: explorer
      POSTGRES_DB: explorer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    # TODO: First time you run it, gotta pull the model. That's kinna dumb
    # entrypoint: ["/bin/sh", "-c", "ollama pull mistral && exec ollama serve"]
    entrypoint: ["/bin/sh", "-c", "exec ollama serve"]
volumes:
  ollama:
  postgres_data:
  redis_data:
